### ISSUE TITLE
What constitutes a MINOR RELEASE

### ISSUE THREAD

**Issue by fulldecent** [USArmyResearchLab/ARL-Open-Source-Guidance-and-Instructions#19]
MINOR RELEASE documentation states:

> Minor releases include all releases that the PD, the PD's OPSEC officer, and the PD's supervisor do not believe require a major review. These include bug fixes and minor updates. A minor release only requires review by a level-1 OPSEC officer before being published. These reviews are called "minor reviews" and are subject to the following:

But "release" is not in the GLOSSARY. Please clarify what a release is. Possible definitions include:

* Every published commit on the `master` or mainline branch
* Every commit, issue, comment, wiki entry, PR
* Every versioned "release" on GitHub as per Semantic Versioning

Since each "release" requires simultaneous approval from "the PD, the PD's OPSEC officer, and the PD's supervisor", the distinction is important.

**Comment by fulldecent** [comment]
Also, the MINOR RELEASE process is sloppy.

> A minor release only requires review by a level-1 OPSEC officer before being published.

conflicts with:

> If a release appears to be a major release in the opinions of any of the PDs, the OPSEC officer, or any of their superiors, then a new ARL Form 1 MUST be filed...

----

Perhaps a better wording would be to start the section with the explicit statements:

> A level-1 OPSEC officer must review the release before being published.

Then, only at the bottom, mention concretely:

> If the PDs, the OPSEC officer, or any of their superiors determine that significant changes to the scope of the project or violation of any of the checks described in this document have occurred or are about to occur, then that person MUST demand that a MAJOR REVIEW occur.

**Comment by ckaran** [comment]
@fulldecent I added in a new glossary term to cover what a release is.  For the second part, do you want to create a PR?  Again, credit where credit is due!

**Comment by ckaran** [comment]
@fulldecent OK, are you comfortable with my closing this issue?

**Comment by fulldecent** [comment]
Yes.
