### ISSUE TITLE
README language is inconsistent

### ISSUE THREAD

**Issue by fulldecent** [USArmyResearchLab/ARL-Open-Source-Guidance-and-Instructions#20]
In the **Code Cleanup and Release Preparation** section, the language:

> A "README" file **MUST** be created at the top level of the directory **with at least** the following in it:

is inconsistent with

> If there is no "VERSION" file, the version number of the release **SHOULD** be included.

---

Recommended correction: 

> Include the version number if there is no "VERSION" file

**Comment by ckaran** [comment]
Pull request?  Credit where credit is due!

**Comment by ckaran** [comment]
@fulldecent I merged in your PR, I'm closing this issue.
