### ISSUE TITLE
Major reviews -- note of specific types of information to scrub

### ISSUE THREAD

**Issue by fulldecent** [USArmyResearchLab/ARL-Open-Source-Guidance-and-Instructions#4]
It may be helpful to specifically mention some types of information that should be scrubbed during major reviews:

* Passwords
* Usernames
* DSN phone numbers
* Links to NIPRNet/SIPRNet

**Comment by fulldecent** [comment]
Fixed here https://github.com/USArmyResearchLab/ARL-Open-Source-Guidance-and-Instructions/commit/5cf41e46d1a6f6d17bc3b407122e398e7c20df67

**Comment by ckaran** [comment]
@fulldecent I merged in your PR, I'm going to close this issue; reopen it if you think I closed it early.
