### ISSUE TITLE
Create a simple example project that others can copy.

### ISSUE THREAD

**Issue by ckaran** [USArmyResearchLab/ARL-Open-Source-Guidance-and-Instructions#7]
Create a simple example project (or maybe projects?) that others can simply copy and modify to their own purposes.

**Comment by fulldecent** [comment]
Good thinking. ALWAYS start a project with copy paste, otherwise you will mess something up.

Here are projects I'm familiar with that are a copy-paste starting point for other projects:

* https://github.com/fulldecent/swift3-module-template
* https://github.com/fulldecent/html-website-template
* https://github.com/CocoaPods/pod-template

In working on these projects I have learned a few things:

* Check lists are good, put them right at the top of the README
* Use informal language addressed to the person whose responsibility it is to initiate the project
* Include hello world functionality, no matter how silly
* The last step of the check list is to delete the checklist and publish the project
* After the check list is done the project should be usable and publishable

---

@ckaran What type of project are you recommending to template? Or can you provide a typical example of an ARL project where you expect more like it will be published in the future?

**Comment by ckaran** [comment]
@fulldecent 'example project' may be more grandiose than what I mean.  Basically, put in a [code.json](https://code.gov/#/policy-guide/docs/compliance/inventory-code) file, a README.md, and maybe a checklist as you suggest.  No actual code, no build system, etc.  The problem with putting in actual code and a build system is then either people get the idea that they can only use certain languages and build systems, or they want examples that cover every possible combination of language and build system.  Neither works well.

**Comment by enckse** [comment]
agreed with @ckaran - what you are suggesting is in line with how github supports a default ".gitignore" or "LICENSE" or "README" (clearly not trying to hit on licensing here, but you can still take a 'default' one).

**Comment by fulldecent** [comment]
Got it. You are talking about:

- [ ] README
  - [ ] Version statement, date, and disclaimer that it is not yet version 1.0
     - No warning like this is necessary because this is not an "official policy" document, it is just a recommendation
       > The master branch of this repository is the only official document; all other branches are for discussion and development only, and may or may not become part of a future official policy.
  - [ ] Following all specifications in Version 1.0.3 process
  - [ ] Add a checklist at the top discussion protocol per Version 1.0.03 process
- [ ] LICENSE
  - [ ] CC0 license
- [ ] code.json
  - [ ] Hello world example
  - [ ] Use https://github.com/USArmyResearchLab/ARL-Open-Source-Guidance-and-Instructions/blob/master/code.json as a starting point
  - [ ] Make any updates per https://code.gov/#/policy-guide/docs/compliance/inventory-code

I just need your help to:

- [ ] Create an empty repository at https://github.com/USArmyResearchLab/ARL-Software-Template 
- [ ] Set the description at the top to
    > Use this template as a starting point for any U.S. Army Research Laboratory (ARL) software release

And then I can help from there.

**Comment by ckaran** [comment]
@fulldecent Do you mind if we keep everything within this repository?  I'm thinking that I can restructure the README so that it has a link pointing to the official guidance, a link pointing to examples, etc.  The advantage is that people can simply pull one repository and know that they have the latest and greatest, rather than worrying about looking for multiple repositories.

I'll create a `HelloWorld` branch off of `develop` to show what I'm thinking about.

**Comment by fulldecent** [comment]
Got it, sounds good. Once you give me somewhere to send commits to, that where they'll start coming.

**Comment by ckaran** [comment]
@fulldecent It's up on the `HelloWorld` branch.

**Comment by fulldecent** [comment]
Note for future reference:

ASNI K100.1-1974 -- Safety Code and Requirements for Dry Martinis

http://www.niso.org/apps/group_public/download.php/6140/K100.1-1974%20-%20American%20National%20Standard%20Safety%20Code%20%26%20Requirements%20for%20Dry%20Martinis%20.pdf

Not a joke.

**Comment by fulldecent** [comment]
Here is the pull request:

https://github.com/USArmyResearchLab/ARL-Open-Source-Guidance-and-Instructions/pull/21

Notes:

* This process documents code.json as an official ARL requirement even though that has not happened yet.
* Language is SLIGHTLY casual. I am champion for lighthearted language specifically to motivate people to complete long checklists or read standards that they might not really care about. Precedent is documented in *ASNI K100.1-1974 -- Safety Code and Requirements for Dry Martinis*.
* I took liberty in interpreting "release" as a version release, discussion in #19.
* I took liberty in deciding which SHOULD/RECOMMEND parts are included in the checklist and which are referenced as "you should read the full ARL process for details".

Other than above caveats, I represent this contribution as fully documenting the ARL release process.

**Comment by ckaran** [comment]
@fulldecent I merged the PR in earlier, with some minor grammar fixes (adding periods, etc.).  I'm waiting for [OSI](http://www.opensource.org) to decide if CC0 is fully Open Source before I make some changes to how licensing is supposed to work (which will affect the checklist).  At that point I'll get to work with really combing through the `develop` branch to get it into shape to send up to the Director for his signature, which will bump the version number to 1.1.0.

**Comment by fulldecent** [comment]
My prior caveat:

 > I took liberty in interpreting "release" as a version release, discussion in #19.

is resolved in #24 and based on discussion in #19.

**Comment by ckaran** [comment]
OK, so are you comfortable with my closing this issue?

**Comment by fulldecent** [comment]
Yes! And thank you for the update about OSI. Thank you for keeping this moving.

**Comment by ckaran** [comment]
👍  Don't worry, I'm going to keep pushing until I'm satisfied that we're doing Open Source about as well as we can under the various laws, regulations, and rules that we have to operate under.  

BTW, if you want to follow the licensing discussions, you can join the [license-discuss](https://opensource.org/lists) mailing list.
